- packages/gnome-shell/scripts/generate-files.js
- packages/gnome-shell/src/extensions/prefs.d.ts
- packages/gnome-shell/src/extensions/sharedInternals.d.ts
Hey @JumpLink , 
they new package you provided is great! I was able to boil down my type definitions file to basically this
`gnome-shell.d.ts`
```ts
/// <reference path="./node_modules/@girs/gjs/dom.d.ts" />
/// <reference path="./node_modules/@girs/gnome-shell/dist/index-ambient.d.ts" />
```
**Very nice!**
There are only two minor issues with the beta package that prevents me from using it currently. Both of which I address in this PR.
---
The first one is very minor: The `schema` argument passed to [ExtensionBase::getSettings](https://github.com/gjsify/gnome-shell/blob/main/packages/gnome-shell/src/extensions/sharedInternals.d.ts#L78) is **optional** (See [source code](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/js/extensions/sharedInternals …
> Fix exported resource:// path for ExtensionPreferences

- packages/gnome-shell/src/misc/extensionUtils.d.ts
- packages/gnome-shell/src/misc/loginManager.d.ts
- packages/gnome-shell/src/misc/systemActions.d.ts
- packages/gnome-shell/src/types/extension-metadata.ts
- packages/gnome-shell/src/ui/main.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
- packages/gnome-shell/src/ui/modalDialog.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
- packages/gnome-shell/src/ui/slider.d.ts
- packages/gnome-shell/src/ui/status/system.d.ts
- packages/gnome-shell/src/ui/status/thunderbolt.d.ts
- packages/gnome-shell/src/ui/status/volume.d.ts
This pull request addresses a few issues I stumbled upon while trying to move from my hand-written types to the types in this repo.    It's by no means complete (there were more issues), but I'm stuck in the process due to some other issues (see #10), so I figured I'd open a merge request with what I already got.
Recommended review is commit by commit, as every commit addresses one problem.
> Improve type definitions

- examples/hello-world/src/extension.ts
- packages/gnome-shell/README.md
- packages/gnome-shell/package.json
- packages/gnome-shell/scripts/generate-exports.js
- packages/gnome-shell/scripts/generate-files.js
- packages/gnome-shell/scripts/generate-index.js
- packages/gnome-shell/scripts/generate-types.js
- packages/gnome-shell/src/extensions/global.d.ts
Closes #12
Add a new `global.d.ts` module with global shell variables and monkey-patches, see #12.  Currently, it's a separate module you'd need to import separately to bring in the global declarations (see changes to the example), but since these are global (i.e. exist regardless of any imports) should I add them to `index-ambient`?
> Add global shell types

- packages/gnome-shell/package.json
- packages/gnome-shell/src/ui/extensionSystem.d.ts
- packages/gnome-shell/src/ui/main.d.ts
Adds types for the ExtensionManager class
> Define extension system types

- packages/gnome-shell/src/ui/extensionSystem.d.ts
Fix implicit "any" return type
> Add missing return type

- packages/gnome-shell/src/extensions/global.d.ts
- packages/gnome-shell/src/ui/extensionSystem.d.ts
- packages/gnome-shell/src/ui/panel.d.ts
- packages/gnome-shell/src/ui/panelMenu.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
> Port some types to GNOME 46

- packages/gnome-shell/src/ui/dateMenu.d.ts
Mark DateMenuButton for GNOME 46, and remove all other types which are not exported anymore in GNOME 46.
> Update dateMenu for GNOME 46

- packages/gnome-shell/src/ui/messageList.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
Update message list and message tray types.
> Update message tray and message list types

- packages/gnome-shell/package.json
- packages/gnome-shell/src/ui/dialog.d.ts
- packages/gnome-shell/src/ui/layout.d.ts
- packages/gnome-shell/src/ui/lightbox.d.ts
- packages/gnome-shell/src/ui/modalDialog.d.ts
This ports some types to GNOME 46 and adds a new file: 
[ui/lightbox](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/lightbox.js)
This fixes only types, I need for an extension, and some things that changed, that I saw while doing that.
> Port some types to GNOME 46 + some additional types

- packages/gnome-shell/src/ui/lightbox.d.ts
- packages/gnome-shell/tsconfig.json
These are already declared by Clutter.Actor, and our declarations are conflicting because they omit null.
Fixes the following compiler errors:
```
node_modules/.pnpm/@girs+gnome-shell@46.0.0-beta4/node_modules/@girs/gnome-shell/dist/ui/lightbox.d.ts:49:22 - error TS2320: Interface 'ConstructorProperties' cannot simultaneously extend types 'ConstructorProperties' and 'LightboxAdditionalParameters'.
Named property 'height' of types 'ConstructorProperties' and 'LightboxAdditionalParameters' are not identical.
49     export interface ConstructorProperties extends St.Bin.ConstructorProperties, LightboxAdditionalParameters {
~~~~~~~~~~~~~~~~~~~~~
node_modules/.pnpm/@girs+gnome-shell@46.0.0-beta4/node_modules/@girs/gnome-shell/dist/ui/lightbox.d.ts:49:22 - error TS2320: Interface …
```
> Remove redundant width and height

- packages/gnome-shell/src/ui/popupMenu.d.ts
The `PopupMenu` class has an `actor` member of type `BoxPointer` that's used when setting up a menu for a panel indicator. It's defined here: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/popupMenu.js?#L879
An example of this member being accessed from outside the class can be found here: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/gdm/loginDialog.js#L337
When implementing a menu for an indicator, you would do something like this:
```ts
class MyIndicatorMenu extends PopupMenu.PopupMenu {
constructor(sourceActor: St.Widget, arrowAlignment: number, arrowSide: St.Side) {
super(sourceActor, arrowAlignment, arrowSide);
Main.uiGroup.add_child(this.actor);
this.actor.hide();
this.addAction("Some action", () => { });
}
}
```
Without this addition you have to resort to …
> Add missing `actor` member on `PopupMenu`

- packages/gnome-shell/src/ui/animation.d.ts
- packages/gnome-shell/src/ui/appDisplay.d.ts
- packages/gnome-shell/src/ui/audioDeviceSelection.d.ts
- packages/gnome-shell/src/ui/background.d.ts
- packages/gnome-shell/src/ui/barLevel.d.ts
- packages/gnome-shell/src/ui/boxpointer.d.ts
- packages/gnome-shell/src/ui/calendar.d.ts
- packages/gnome-shell/src/ui/checkBox.d.ts
- packages/gnome-shell/src/ui/dialog.d.ts
- packages/gnome-shell/src/ui/dnd.d.ts
- packages/gnome-shell/src/ui/iconGrid.d.ts
- packages/gnome-shell/src/ui/layout.d.ts
- packages/gnome-shell/src/ui/lightbox.d.ts
- packages/gnome-shell/src/ui/messageList.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
- packages/gnome-shell/src/ui/modalDialog.d.ts
- packages/gnome-shell/src/ui/mpris.d.ts
- packages/gnome-shell/src/ui/panelMenu.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
- packages/gnome-shell/src/ui/quickSettings.d.ts
- packages/gnome-shell/src/ui/search.d.ts
- packages/gnome-shell/src/ui/switcherPopup.d.ts
Since the new Beta of `ts-for-gir` the approach to optional parameters has changed, now everywhere `Partial<XY.ConstructorProps>` is used, instead of declaring each property in the `ConstructorProps` `property?: xy `
This breaks many things, and they all have to be changed, this wasn't caught before, since apparently no-one (including me) used the `4.0.0-beta.2` types.
I'll try to find all places and then squash it into one commit.
Here's a fun screenshot, of using this types with the `beta-2` packages:
> Beta fixes: Optional Properties handling

- packages/gnome-shell/src/extensions/extension.d.ts
- packages/gnome-shell/src/ui/components/automountManager.d.ts
- packages/gnome-shell/src/ui/components/autorunManager.d.ts
1. Removed import of ExtensionType and ExtensionState, which are not used in the file
2. Removed unnecessary ambient imports
3. Added comments for consistency with other files
> declarations cleanup

- packages/gnome-shell/src/ui/messageTray.d.ts
We're using a separate object properties interface down below.
> Remove unused Params interface

- packages/gnome-shell/package.json
- packages/gnome-shell/src/ui/layout.d.ts
- packages/gnome-shell/src/ui/lookingGlass.d.ts
- packages/gnome-shell/src/ui/windowPreview.d.ts
- packages/gnome-shell/src/ui/workspace.d.ts
- packages/gnome-shell/src/ui/workspaceAnimation.d.ts
- packages/gnome-shell/src/ui/workspacesView.d.ts
Add extra types required for the https://github.com/flexagoon/rounded-window-corners extension
> Add types for rounded-window-corners

- packages/gnome-shell/src/ui/quickSettings.d.ts
Also contains general improvements such as addition of missing types
closes #40
> ui/quickSettings.d.ts: add constructor props

- examples/hello-world/package.json
- package.json
- packages/gnome-shell/package.json
- packages/gnome-shell/src/ui/workspace.d.ts
- packages/gnome-shell/src/ui/workspacesView.d.ts
I just tried to upgrade my extension to the latest versions of `@girs/*` packages and noticed that two errors from `tsc`. I would release a new version after approval by one of the other contributors :).
```sh
> tsc --noEmit
node_modules/@girs/gnome-shell/dist/ui/workspace.d.ts:4:31 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './windowPreview.js'?
4 import { WindowPreview } from './windowPreview';
~~~~~~~~~~~~~~~~~
node_modules/@girs/gnome-shell/dist/ui/workspacesView.d.ts:1:27 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './workspace.js'?
1 import { Workspace } from …
```
> Fix ambient import

- README.md
Hey guys!
While issuing my last PR, I saw that the README.md file now contains a _Showcase_ section. I would like to add the `gTile` extension to it. I believe it is a good project for newcomers to see `@girs` types being utilized to its full extent.
https://github.com/gTile/gTile
> Showcase: gTile Gnome extension

- README.md
Same as #46 but for the extension Pano, that also uses many types and is fully typed ❤️
> Showcase: Pano Gnome extension

- packages/gnome-shell/package.json
- packages/gnome-shell/src/extensions/prefs.d.ts
- packages/gnome-shell/src/misc/util.d.ts
- packages/gnome-shell/src/ui/messageList.d.ts
Based on the changes listed here: https://gjs.guide/extensions/upgrading/gnome-shell-47.html
---
I am going to test integration with [gTile](https://github.com/gTile/gTile) now and will report back whether I stumbled upon any errors.
> Adapt typings for Gnome 47 release

- .vscode/settings.json
- packages/gnome-shell/src/misc/signals.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
- packages/gnome-shell/src/ui/modalDialog.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
- packages/gnome-shell/src/ui/status/keyboard.d.ts
I checked a few modules I use in one of my extensions.
> Mark a few types for GNOME 47

- packages/gnome-shell/src/misc/animationUtils.d.ts
- packages/gnome-shell/src/types/extension-metadata.ts
- packages/gnome-shell/src/ui/dialog.d.ts
- packages/gnome-shell/src/ui/layout.d.ts
- packages/gnome-shell/src/ui/lightbox.d.ts
- packages/gnome-shell/src/ui/main.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
- packages/gnome-shell/src/ui/panelMenu.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
I checked all modules I use in my extension, and as expected I didn't find many changes.
The last commit may be controversial, as discussed in https://github.com/gjsify/gnome-shell/pull/51 in several comments.
The method `fillPreferencesWindow` is now async, see https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/0f30bfdd531ed0e8ed78bda74d51b7f22872a31b#
But I believe it's better to have a `Promise<void> | void` type, even if the doctoring says, it has to be a Promise, it can also be no promise as the JavaScript usage is only with `await fillPreferencesWindow()` which also works with a non async version of the function. If it would use `.then()` or similar this wouldn't work, but I believe it's better to also allow `void`
See also …
> Mark gnome types for 47

- packages/gnome-shell/src/extensions/extension.d.ts
The type for overrideMethod is pretty complex to offer proper type checking:
- `T` is an object prototype
- `M` is a field name which must exist on that object
- `T[M]` must be a function
- The override method must have the same signature as the original method
- Inside of the override method, `this` has the type `T`
> Add InjectionManager

- packages/gnome-shell/src/extensions/sharedInternals.d.ts
- packages/gnome-shell/src/misc/animationUtils.d.ts
- packages/gnome-shell/src/types/extension-metadata.ts
- packages/gnome-shell/src/ui/calendar.d.ts
- packages/gnome-shell/src/ui/dialog.d.ts
- packages/gnome-shell/src/ui/layout.d.ts
- packages/gnome-shell/src/ui/lightbox.d.ts
- packages/gnome-shell/src/ui/main.d.ts
- packages/gnome-shell/src/ui/messageList.d.ts
- packages/gnome-shell/src/ui/messageTray.d.ts
- packages/gnome-shell/src/ui/mpris.d.ts
- packages/gnome-shell/src/ui/panelMenu.d.ts
- packages/gnome-shell/src/ui/popupMenu.d.ts
- packages/gnome-shell/src/ui/windowManager.d.ts
This PR does two things:
Implement most of the types from the changes described in porting guide [here](https://gjs.guide/extensions/upgrading/gnome-shell-48.html)
check all types I use in my extension, similar to #53
> Improve GNOME 48 types

- examples/hello-world/package.json
- package.json
- packages/gnome-shell/package.json
- packages/gnome-shell/src/ui/messageList.d.ts
- packages/gnome-shell/src/ui/windowManager.d.ts
Same issue as in #45
I've already released this a hotfix (48.0.1) to the NPM registry, so I am going to merge this PR immediately too.
> Hotfix: relative import paths require .js suffix

- examples/hello-world/src/extension.ts
- packages/gnome-shell/src/extensions/extension.d.ts
- packages/gnome-shell/src/extensions/sharedInternals.d.ts
See also https://github.com/gjsify/gnome-shell/pull/61#discussion_r2009115693
This is just a proposal on how to fix the problem from https://github.com/gjsify/gnome-shell/pull/61#discussion_r2009115693
Type duplication is bad, but to convert the class approach one to one, it has to be done. 
I don't think the class is necessary, as it is never really used as class, the constructor i not accessible, all members are private, so only member methods are usable, which make it, from a type perspective equal to an interface.
Edit: I found a way to avoid type duplication: see [here](https://stackoverflow.com/questions/65787571/avoiding-fields-declaration-duplication-in-interface-and-class-definition)
> Fix: Export the Console Interface as `ConsoleLike`

- .github/workflows/build.yml
- .github/workflows/release.yml
- .yarnrc.yml
- examples/hello-world/package.json
- package.json
- packages/gnome-shell/package.json
This is a follow up of #64 
Since I tested #64 at the beginning with npm, setting the enviornment variable `NPM_TOKEN` was enough, as npm picked that up, but yarn doesn't do that and it needs the setting `npmAuthToken` in the `.yarnrc.yml` settings file to be set correctly. 
But when you use that in the CI, the release CI and build CI  fail, as `NPM_TOKEN` is not set everywhere, so it has a default empty value in the CI's .
I tested this entirely with a private registry and it works.
~~This is one possible fix of the release CI, see #72 for the 2. option (which doesn't work)~~
> Fix yarn authentication in release CI (option 1)

- README.md
I noticed, that we (I) didn't adjuts the action url, after modifying it from ci.yml to build.yml, this fixes that.
> fix the build.yml action file in the readme
